### ISSUE TITLE
bug in mtefunctions.pas

### ISSUE THREAD

**Issue by comiluv** [matortheeternal/mxpf#10]
in function GetChar;
function GetChar(const s: string; n: integer): char;
begin
  Result := Copy(s, n, 1);
end;

should be;
function GetChar(const s: string; n: integer): char;
begin
  if n < 1 then Result := '' else Result := Copy(s, n, 1);
end;

**Comment by matortheeternal** [comment]
there is no character in a string at an index less than 1, does GetChar really need to return an empty string if a user inputs an invalid argument?  I think it'd be better if it just raised an exception if the user inputs a number less than 1.

**Comment by comiluv** [comment]
Then function GetTextIn in the same pas needs fixed. Its current function is:
function GetTextIn(str: string; open, close: char): string;
var
  i, openIndex: integer;
  bOpen: boolean;
begin
  Result := '';
  bOpen := false;
  for i := 0 to Length(str) do begin
    if bOpen and (GetChar(str, i) = close) then break;
    if bOpen then Result := Result + GetChar(str, i);
    if not bOpen and (GetChar(str, i) = open) then bOpen := true;    
  end;
end;

should be:
function GetTextIn(str: string; open, close: char): string;
var
  i, openIndex: integer;
  bOpen: boolean;
begin
  Result := '';
  bOpen := false;
  for i := 1 to Length(str) do begin
    if bOpen and (GetChar(str, i) = close) then break;
    if bOpen then Result := Result + GetChar(str, i);
    if not bOpen and (GetChar(str, i) = open) then bOpen := true;    
  end;
end;

I found this bugging with your Automation Tools for TES5Edit which I still use quite often, recently used NPC Transmogrifier to randomly transmogrify Immersive Patrols and Adventurers and Travelers mod.

**Comment by matortheeternal** [comment]
The current code for `GetTextIn` is:

```pascal
function GetTextIn(str: string; open, close: char): string;
var
  i, openIndex: integer;
  bOpen: boolean;
begin
  Result := '';
  bOpen := false;
  for i := 0 to Length(str) do begin
    if not bOpen and (GetChar(str, i) = open) then begin
      openIndex := i;
      bOpen := true;
    end;
    if bOpen and (GetChar(str, i) = close) then begin
      Result := CopyFromTo(str, openIndex + 1, i - 1);
      break;
    end;
  end;
end;
```

The for loop should start from 1, pushing a fix.
