### ISSUE TITLE
xEdit tries to add "Skyrim.Hardcoded" dat-file as master

### ISSUE THREAD

**Issue by Meridiano** [matortheeternal/mxpf#11]
When I try to  
> LoadRecords('IMAD');

I get error that "Skyrim.Hardcoded.keep.this.with.the.exe.and.otherwise.ignore.it.I.really.mean.it.dat" doest't exist. It seems MXPF tries to load records 164 and 166 from [00] "Skyrim.exe" and add "Skyrim.Hardcoded" as master. Maybe other records from it can cause this error too.

Well, I fixed this by adding  
> and (not StrEndsWith(Lowercase(lst[i]), '.dat'))

in some places (where mteFunctions adds masters).

**Comment by matortheeternal** [comment]
Yeah, I seem to recall hearing about this at some point in time in the past as well.  MXPF is no longer being updated, however, so I'm unlikely to fix this myself.  You can make a PR here on GitHub if you want.

**Comment by Meridiano** [comment]
Thank you for merging.
